@startuml name "addKeyFile"

skin rose
title Сформировать ключ файла

start

if (URL атрибута объекта МосХаба\nсодержит пустую ссылку?) then (да)
    :Значению ключа файла присваивается значение null;
else (нет)
    :Приложение получает файл
    по ссылке из объекта МосХаба;

    :Приложение загружает файл в ФХ;
    if (метод загрузки вернул http-статус = 200?) then (нет)
        :Значению ключа файла присваивается значение id
        из ответа метода загрузки файла;
    else (да)
        :Значению ключа файла присваивается значение null;
    endif
endif

stop
@enduml