@startuml name "commitFile"
skin rose
title Изменение статуса наличия файла лицензии

start

:Вызов функции принятия изменений коммита;

switch (Проверка типа производимого действия)
case (загружается новый файл?)
    if (Имя файла удовлетворяет проверке RegEx?) then (да)
      if (Ранее файл лицензии существовал?) then (нет)
      :Изменение статуса наличия лицензии на true,
      сохранение относительной ссылки для просмотра файла;
      else (да)
      endif
    else (нет)
    endif
case (удаляется существующий файл?)
    if (Имя файла удовлетворяет проверке RegEx?) then (да)
      if (Имя и путь файла совпадает с сохраненным) then (да)
        if (В папке есть ещё файлы, удовлетворяющие проверке RegEx?) then (нет)
          :Изменение статуса наличия лицензии на false,
          сохранение относительной ссылки для просмотра файла как null;
        else (да)
          :Cохранение относительной ссылки для другого файла;    
        endif
      else (нет)
      endif      
    else (нет)
    endif
case (переименовывается существующий файл?)
    if (Старое имя файла удовлетворяет проверке RegEx?) then (да)
      if (Имя и путь файла совпадает с сохраненным) then (да)
        if (Новое имя файла удовлетворяет проверке RegEx?) then (да)
          :Cохранение относительной ссылки для нового имени;
        else (нет)
          if (В папке есть ещё файлы, удовлетворяющие проверке RegEx?) then (нет)
            :Изменение статуса наличия лицензии на false,
            сохранение относительной ссылки для просмотра файла как null;
          else (да)
            :Cохранение относительной ссылки для другого файла;    
          endif
        endif
      else (нет)
      endif
    else (нет)
      if (Новое имя файла удовлетворяет проверке RegEx?) then (да)
           if (Ранее файл лицензии существовал?) then (нет)
            :Изменение статуса наличия лицензии на true,
            cохранение относительной ссылки для нового имени;
          else (да)
          endif
      else (нет)
      endif
    endif
case (другое?)
endswitch
stop

@enduml